# TCL File Generated by Component Editor 11.0
# Thu Feb 02 14:51:38 CET 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | multiply "multiply" v1.0
# | null 2012.02.02.14:51:38
# | 
# | 
# | C:/IHA/ETDSPC/Code/mySopc/multiply.vhd
# | 
# |    ./multiply.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module multiply
# | 
set_module_property NAME multiply
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME multiply
set_module_property TOP_LEVEL_HDL_FILE multiply.vhd
set_module_property TOP_LEVEL_HDL_MODULE multiply
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file multiply.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios_custom_instruction_slave_0
# | 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 2

set_interface_property nios_custom_instruction_slave_0 ENABLED true

add_interface_port nios_custom_instruction_slave_0 dataa multi_n Input 8
add_interface_port nios_custom_instruction_slave_0 datab multi_n Input 8
add_interface_port nios_custom_instruction_slave_0 result export Output 8
# | 
# +-----------------------------------
