# TCL File Generated by Component Editor 12.1
# Thu Apr 04 18:26:07 CEST 2013
# DO NOT MODIFY


# 
# RAM_Sound "RAM_Sound" v1.1
# null 2013.04.04.18:26:07
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module RAM_Sound
# 
set_module_property NAME RAM_Sound
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP IHA
set_module_property DISPLAY_NAME RAM_Sound
set_module_property TOP_LEVEL_HDL_FILE Syntezise.vhd
set_module_property TOP_LEVEL_HDL_MODULE Syntezise
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME Syntezise
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file RamAccess.vhd {SYNTHESIS SIMULATION}
add_file TransferProtocol.vhd {SYNTHESIS SIMULATION}
add_file PlaySound.vhd {SYNTHESIS SIMULATION}
add_file Syntezise.vhd {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 
add_parameter ramSize NATURAL 512 ""
set_parameter_property ramSize DEFAULT_VALUE 512
set_parameter_property ramSize DISPLAY_NAME ramSize
set_parameter_property ramSize TYPE NATURAL
set_parameter_property ramSize UNITS None
set_parameter_property ramSize ALLOWED_RANGES 0:2147483647
set_parameter_property ramSize DESCRIPTION ""
set_parameter_property ramSize HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock_12M
set_interface_property s1 associatedReset clock_12M_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 8
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_12M
set_interface_property avalon_streaming_source associatedReset clock_12M_reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 24
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source ast_source_data data Output 24
add_interface_port avalon_streaming_source ast_source_ready ready Input 1
add_interface_port avalon_streaming_source ast_source_valid valid Output 1
add_interface_port avalon_streaming_source ast_source_error error Output 2


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_12M
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point clock_50M
# 
add_interface clock_50M clock end
set_interface_property clock_50M clockRate 0
set_interface_property clock_50M ENABLED true

add_interface_port clock_50M csi_clockreset_clk clk Input 1


# 
# connection point clock_12M
# 
add_interface clock_12M clock end
set_interface_property clock_12M clockRate 0
set_interface_property clock_12M ENABLED true

add_interface_port clock_12M ast_clk clk Input 1

