# TCL File Generated by Component Editor 11.0
# Thu Feb 02 14:54:04 CET 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | multiplierAdd "MultiplierAdd" v1.0
# | null 2012.02.02.14:54:04
# | 
# | 
# | C:/IHA/ETDSPC/Code/mySopc/multiplierAdd.vhd
# | 
# |    ./multiplierAdd.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module multiplierAdd
# | 
set_module_property NAME multiplierAdd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME MultiplierAdd
set_module_property TOP_LEVEL_HDL_FILE multiplierAdd.vhd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file multiplierAdd.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------
